using DocCreator01.Data.Enums;
using System;
using System.IO;

namespace DocCreator01.Models
{
    /// <summary>
    /// Represents a file that has been generated by the application
    /// </summary>
    public class GeneratedFile
    {
        /// <summary>
        /// The full path to the generated file
        /// </summary>
        public string FilePath { get; set; } = string.Empty;
        
        /// <summary>
        /// The type of generated document
        /// </summary>
        public GenerateFileTypeEnum FileType { get; set; }
        
        /// <summary>
        /// Gets the file name from the full path
        /// </summary>
        public string FileName => Path.GetFileName(FilePath);
        
        /// <summary>
        /// Gets the file extension without the dot
        /// </summary>
        public string Extension => Path.GetExtension(FilePath).TrimStart('.');
        
        /// <summary>
        /// Checks if the file exists on disk
        /// </summary>
        public bool Exists => File.Exists(FilePath);
        
        /// <summary>
        /// Reference to the parent project (needed for deletion operations)
        /// </summary>
        public Project Project { get; set; }
    }
}
